#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SECRETS_FILE="${1:-$ROOT_DIR/.secrets.env}"
WRANGLER_CONFIG_PATH="$ROOT_DIR/wrangler.jsonc"
DEV_VARS_PATH="$ROOT_DIR/.dev.vars"

if [[ ! -f "$SECRETS_FILE" ]]; then
  echo "Secrets file not found: $SECRETS_FILE" >&2
  exit 1
fi

set -a
# shellcheck source=/dev/null
source "$SECRETS_FILE"
set +a

if [[ ! -f "$WRANGLER_CONFIG_PATH" ]]; then
  echo "wrangler.jsonc not found: $WRANGLER_CONFIG_PATH" >&2
  exit 1
fi

write_dev_var() {
  local file_path="$1"
  local key="$2"
  local value="$3"
  printf "%s=%s\n" "$key" "$value" >> "$file_path"
}

tmp_dev_vars="$(mktemp)"
chmod 600 "$tmp_dev_vars"
{
  printf "# Generated by scripts/set-secrets.sh\n"
  printf "# Local Wrangler dev secrets/overrides.\n\n"
} > "$tmp_dev_vars"

write_dev_var "$tmp_dev_vars" "APP_URL" "${APP_URL_DEV:-${APP_URL:-http://192.168.17.2:8787}}"
write_dev_var "$tmp_dev_vars" "SESSION_SECRET" "${SESSION_SECRET:-}"
write_dev_var "$tmp_dev_vars" "OAUTH_DISCORD_CLIENT_SECRET" "${OAUTH_DISCORD_CLIENT_SECRET:-}"

mv "$tmp_dev_vars" "$DEV_VARS_PATH"
echo "Wrote local dev vars to $DEV_VARS_PATH"

echo "Syncing wrangler.jsonc from $SECRETS_FILE"
ROOT_DIR="$ROOT_DIR" node <<'NODE'
const fs = require("node:fs");
const path = require("node:path");
const { parse } = require("jsonc-parser");

const root = process.env.ROOT_DIR;
const configPath = path.join(root, "wrangler.jsonc");
const raw = fs.readFileSync(configPath, "utf8");
const config = parse(raw) || {};

const envVar = (name) => {
  const value = process.env[name];
  return typeof value === "string" ? value : "";
};

const fallback = (value, alt) => (value && value.length > 0 ? value : alt);

const appUrlDev = fallback(envVar("APP_URL_DEV"), envVar("APP_URL"));
const appUrlStaging = fallback(envVar("APP_URL_STAGING"), appUrlDev);
const appUrlProduction = fallback(envVar("APP_URL_PRODUCTION"), appUrlStaging);

const discordClientId = envVar("OAUTH_DISCORD_CLIENT_ID");
const discordGuildId = envVar("DISCORD_GUILD_ID");
const discordRoleAdmin = envVar("DISCORD_ROLE_ADMIN");
const discordRoleEditor = envVar("DISCORD_ROLE_EDITOR");
const discordClientIdStaging = fallback(envVar("OAUTH_DISCORD_CLIENT_ID_STAGING"), discordClientId);
const discordGuildIdStaging = fallback(envVar("DISCORD_GUILD_ID_STAGING"), discordGuildId);
const discordRoleAdminStaging = fallback(envVar("DISCORD_ROLE_ADMIN_STAGING"), discordRoleAdmin);
const discordRoleEditorStaging = fallback(envVar("DISCORD_ROLE_EDITOR_STAGING"), discordRoleEditor);
const discordClientIdProduction = fallback(envVar("OAUTH_DISCORD_CLIENT_ID_PRODUCTION"), discordClientIdStaging);
const discordGuildIdProduction = fallback(envVar("DISCORD_GUILD_ID_PRODUCTION"), discordGuildIdStaging);
const discordRoleAdminProduction = fallback(envVar("DISCORD_ROLE_ADMIN_PRODUCTION"), discordRoleAdminStaging);
const discordRoleEditorProduction = fallback(envVar("DISCORD_ROLE_EDITOR_PRODUCTION"), discordRoleEditorStaging);

const sessionCookieName = fallback(envVar("SESSION_COOKIE_NAME"), "dgl_session");
const d1DatabaseId = envVar("D1_DATABASE_ID");
const kvNamespaceId = envVar("KV_NAMESPACE_ID");

config.vars ||= {};
config.vars.APP_URL = fallback(appUrlDev, config.vars.APP_URL || "http://192.168.17.2:8787");
config.vars.SESSION_COOKIE_NAME = sessionCookieName;
config.vars.OAUTH_DISCORD_CLIENT_ID = discordClientId;
config.vars.DISCORD_GUILD_ID = discordGuildId;
config.vars.DISCORD_ROLE_ADMIN = discordRoleAdmin;
config.vars.DISCORD_ROLE_EDITOR = discordRoleEditor;

config.env ||= {};
config.env.staging ||= {};
config.env.staging.vars ||= {};
config.env.staging.vars.APP_URL = fallback(appUrlStaging, config.env.staging.vars.APP_URL || "https://dailies-stg.0x9.ca");
config.env.staging.vars.SESSION_COOKIE_NAME = sessionCookieName;
config.env.staging.vars.OAUTH_DISCORD_CLIENT_ID = discordClientIdStaging;
config.env.staging.vars.DISCORD_GUILD_ID = discordGuildIdStaging;
config.env.staging.vars.DISCORD_ROLE_ADMIN = discordRoleAdminStaging;
config.env.staging.vars.DISCORD_ROLE_EDITOR = discordRoleEditorStaging;

config.env.production ||= {};
config.env.production.vars ||= {};
config.env.production.vars.APP_URL = fallback(appUrlProduction, config.env.production.vars.APP_URL || "https://dailies.0x9.ca");
config.env.production.vars.SESSION_COOKIE_NAME = sessionCookieName;
config.env.production.vars.OAUTH_DISCORD_CLIENT_ID = discordClientIdProduction;
config.env.production.vars.DISCORD_GUILD_ID = discordGuildIdProduction;
config.env.production.vars.DISCORD_ROLE_ADMIN = discordRoleAdminProduction;
config.env.production.vars.DISCORD_ROLE_EDITOR = discordRoleEditorProduction;

const setBindingIds = (target) => {
  if (!target.d1_databases || target.d1_databases.length === 0) {
    return;
  }
  if (!target.kv_namespaces || target.kv_namespaces.length === 0) {
    return;
  }
  if (d1DatabaseId) {
    target.d1_databases[0].database_id = d1DatabaseId;
  }
  if (kvNamespaceId) {
    target.kv_namespaces[0].id = kvNamespaceId;
  }
};

setBindingIds(config);
setBindingIds(config.env.staging);
setBindingIds(config.env.production);

fs.writeFileSync(configPath, `${JSON.stringify(config, null, 2)}\n`, "utf8");
NODE

put_secret() {
  local secret_name="$1"
  local secret_value="$2"
  local env_name="$3"
  local tmp_file

  if [[ -z "$secret_value" ]]; then
    return 0
  fi

  tmp_file="$(mktemp)"
  chmod 600 "$tmp_file"
  printf "%s" "$secret_value" > "$tmp_file"

  if [[ -n "$env_name" ]]; then
    npx wrangler secret put "$secret_name" --env "$env_name" < "$tmp_file"
  else
    npx wrangler secret put "$secret_name" --env "" < "$tmp_file"
  fi

  rm -f "$tmp_file"
}

put_secret "SESSION_SECRET" "${SESSION_SECRET:-}" ""
put_secret "SESSION_SECRET" "${SESSION_SECRET_STAGING:-${SESSION_SECRET:-}}" "staging"
put_secret "SESSION_SECRET" "${SESSION_SECRET_PRODUCTION:-${SESSION_SECRET:-}}" "production"

put_secret "OAUTH_DISCORD_CLIENT_SECRET" "${OAUTH_DISCORD_CLIENT_SECRET:-}" ""
put_secret "OAUTH_DISCORD_CLIENT_SECRET" "${OAUTH_DISCORD_CLIENT_SECRET_STAGING:-${OAUTH_DISCORD_CLIENT_SECRET:-}}" "staging"
put_secret "OAUTH_DISCORD_CLIENT_SECRET" "${OAUTH_DISCORD_CLIENT_SECRET_PRODUCTION:-${OAUTH_DISCORD_CLIENT_SECRET:-}}" "production"

echo "Secrets uploaded for default, staging, and production environments."
